apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 80         # Port Service
    targetPort: 3800 # Container Port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: susguzman/so1-s223-back:0.1.1
        env:
        - name: ORACLE_USER
          value: APPUSER
        - name: ORACLE_PASS
          value: passwordapp
        - name: ORACLE_CONNSTR
          value: database-svc:1521/xepdb1
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3800
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hta-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
