apiVersion: v1
kind: Service
metadata:
  name: database-svc
spec:
  type: ClusterIP # Private Service
  selector:
    app: database
  ports:
  - port: 1521
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: gvenzl/oracle-xe:21.3.0
        env:
        - name: ORACLE_PASSWORD
          value: passwordso1
        - name: APP_USER_PASSWORD
          value: passwordapp
        - name: APP_USER
          value: APPUSER
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m" # 1 CPU
        ports:
        - containerPort: 1521
